"use strict";

import * as def from "webinate-users";
import {ClientConnection} from "./client-connection";

/**
 * An instruction that is generated by the server and sent to relevant clients.
 */
export class ClientInstruction<T extends def.SocketEvents.IToken>
{
    /**
     * Specify a username that if set, will only send this instruction to authorized clients
     * and/or the spefic user who may be connected
     */
    username: string;

    /**
     * An array of clients to send the instruction to. If null, then all clients will be considered
     */
    recipients: ClientConnection[];

    /**
     * The event sent from the client
     */
    token: T;

    constructor(event: T, client: ClientConnection[] = null, username : string = null )
    {
        this.recipients = client;
        this.token = event;
        this.username = username;
    }
}